### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by SindhujaD** [Coders-Central/Coders-Central.github.io#1]
Does anybody know how to make it so that we can have pages like coders-central.github.to/contact or some thing like that rather than just having one page (coders-central.github.io)?

**Comment by Solusin** [comment]
I'm sure we can make one by default just by creating the file, and I guess to do it we'd link it to the file.

**Comment by SindhujaD** [comment]
I'll try I found this link that explains how to, http://webapps.stackexchange.com/questions/42455/publishing-more-than-one-site-on-github-pages
