### ISSUE TITLE
Alerts are for debugging

### ISSUE THREAD

**Issue by ABaker86** [Coders-Central/Coders-Central.github.io#11]
Although the only function in the website's JavaScript source is a call to an Alert, I think that it needs to be removed. Alerts should only be used for learning and testing and should not be part of the master branch of any project. Besides, it is kind of distracting when navigating to the home page of the website simply to have a large portion of your screen be covered up by a pop-up that say "welcome".

**Comment by mektrode** [comment]
Just out of curiosity, what is your experience level in web development?

-----Original Message-----

**Comment by ABaker86** [comment]
Most of my development experience is focused in Java and C#. I have recently acquired a Bachelors of Information Technology with a focus in Software Development and Analysis. Several years ago I worked with as a network administrator for my community grad school. I have also got a few years of experience working with web technologies building websites from scratch, WordPress, and I have recently published my first Google Chrome Packaged App.

**Comment by SindhujaD** [comment]
Your pretty experienced compared to me! I have been learning online for
some time, and I have been getting better. I think that we can completely
redo the website because most of us probably are a lot better now. Do you
guys think that we should use bootstrap?

**Comment by ABaker86** [comment]
Before we go jumping the gun too much on what technologies should be used on a redesign, I think that you should take a look at the simple response design I have created in my profile. I have made a pull request that everyone should be able to view here. The design uses the previous Web site's background image and a little CSS magic to add some :sparkles: to the design. The layout is currently responsive, meaning that elements on the screen reorganize themselves to fit on different device screens. 

As far as Bootstrap is concerned, I have limited experience working with it, but I am not against learning a new tool.

**Comment by ABaker86** [comment]
Is Solusin still active on this project?
How do contributors of this project communicate I would like to get in touch without flooding an issues marker with unwarranted communication? (email, messenger, etc.)

**Comment by SindhujaD** [comment]
I have no idea... I'll check

**Comment by mektrode** [comment]
We can pick up and finish this website by end of this week if we get serious. I believe all the experience we need is within the group now.
Y'll down to grind?

-----Original Message-----

**Comment by SindhujaD** [comment]
Yup!

**Comment by ABaker86** [comment]
I suppose I can still help, but are you expecting each of us to make modifications directly to the master branch of the Web Page. This will cause problems when each of us try to make modifications because each committed modification will overwrite the code of the next.

**Comment by ABaker86** [comment]
Can either of you accept a pull request? I keep trying to make adjustments but i don't have write access to the organization repo.

**Comment by mektrode** [comment]
Welcome aboard Adam

-----Original Message-----
