### ISSUE TITLE
A cloud database is very possible.

### ISSUE THREAD

**Issue by mektrode** [Coders-Central/Coders-Central.github.io#16]
Guys i've been working with Parse for a long time now and its the easiest option for a cloud database. I'll get onto integrating it into the website this weekend.

**Comment by mektrode** [comment]
In the meantime, Adam and SindhujaD, could you guys create some username/password fields for both new and current users with error msgs and the lot.

**Comment by mektrode** [comment]
Also have a start in thinking about the design/html code for the forum. I can get all the backend js for that up and running soon as well.

**Comment by ABaker86** [comment]
I don't know anything about Parse, but if you think it is doable lets gets get it done. We will be counting on you for implementation and testing.

**Comment by mektrode** [comment]
I'm going to need to create a new parse account for everyone here to access the database. Look at my new issue on it.
