### ISSUE TITLE
Dynamically update Date in footer

### ISSUE THREAD

**Issue by ABaker86** [Coders-Central/Coders-Central.github.io#19]
Dose anyone want to tackle implementing a dynamic date in the footer of the Web page?
i.e. instead of having to update the second date in the footer manually each year, we can do this with JavaScript or jQuery automatically when the page loads. 

:date:

**Comment by mektrode** [comment]
Busy working on the database, but it should'nt be a problem if you go ahead with it

**Comment by ABaker86** [comment]
I'm on it.

**Comment by ABaker86** [comment]
A dynamic date in the footer has been applied.
