### ISSUE TITLE
CSS Problems

### ISSUE THREAD

**Issue by Solusin** [Coders-Central/Coders-Central.github.io#2]
We really need to step up with the CSS coding. I did a little fixing but whats mainly bothering me is the size of the div's and the Login and Signup buttons positioning.
The divs are too small for the entire page, and the Buttons are being pushed over by the Title. Lets just work on this ok?

**Comment by mektrode** [comment]
I've done some major work on the css a couple hrs ago... but dude get ur hands dirty and keep trying. If you could be more specific on what ur having problems with then thats kl.

**Comment by Solusin** [comment]
To be honest, you undid the major change I did yesterday, mostly about the height of the divs, that you shrunk.

**Comment by mektrode** [comment]
I made the height of all those divs auto. So the height will depend on the amount of content in the div. If u want to make its longer... feel free man.

**Comment by Solusin** [comment]
Ok, It just kind of confused me why you did that.

**Comment by mektrode** [comment]
Tbh i dont know why i do half the shit i do either, yo i just do.
