### ISSUE TITLE
The Contributor Page

### ISSUE THREAD

**Issue by ABaker86** [Coders-Central/Coders-Central.github.io#22]
I think that we should add a contributors/members page to the Site. I think the best and fastest way to do this is by using the current index as a `master-page` and making a few modifications to the HMTL. (copy it=> Rename it=> modify it). This process could be done with most of the additional pages added.

**Comment by mektrode** [comment]
What? You mean with sections with more information about the contributors, I think that's a good idea. Go ahead with it

**Comment by ABaker86** [comment]
That is exactly what I was thinking. I though that if anyone contributor or member wanted to use the sight as a resume resource during an interview they would have the ability to physically show that they are members of the community. Additionally, I though it would be a good means of providing others with more information about member experience.
