### ISSUE TITLE
Somethings up with the sign-in code

### ISSUE THREAD

**Issue by mektrode** [Coders-Central/Coders-Central.github.io#25]
Working on it

**Comment by ABaker86** [comment]
What

**Comment by ABaker86** [comment]
didn't mean to close the issues. -hit the wrong button.

**Comment by ABaker86** [comment]
Is this something that you may need help with? I don't know Parse, but I can look into it if you think that you will need a hand.

**Comment by mektrode** [comment]
Im good for now. Start working on the sign up section if u can

**Comment by mektrode** [comment]
Fixed it. Now you can sign up or login

**Comment by SindhujaD** [comment]
:-)
