### ISSUE TITLE
Contributers

### ISSUE THREAD

**Issue by SindhujaD** [Coders-Central/Coders-Central.github.io#26]
Should we replace Solusin's spot on the page with Adam's? Soludin isn't really active on the project anymore.

**Comment by ABaker86** [comment]
I don't think that It would be a good idea to replace any images of individuals that have contributed regardless of their activity. As I mentioned before I think that it would be better to replace the static images with a dynamic image carousal or slider for those that continue to contribute.

**Comment by SindhujaD** [comment]
That's a smart idea, that way we can add everyone that has contributed.
