### ISSUE TITLE
Sign In

### ISSUE THREAD

**Issue by SindhujaD** [Coders-Central/Coders-Central.github.io#27]
To sign in, do you want to use the email as a sign in rather than a different user name? That way we won't have to store as much information and it will be easier for the user.

**Comment by ABaker86** [comment]
This is a good point. As I said before. I don't know anything about Parse as a back-end database so M-Hc0d3 will have to let us know if the userName/Password can contain values commonly used in email addresses `@` and `.`

**Comment by mektrode** [comment]
Bakers right, Parse requires text based usernames

**Comment by SindhujaD** [comment]
oh, okay. Got it
