### ISSUE TITLE
Problem with securty

### ISSUE THREAD

**Issue by NE1W01F** [Coders-Central/Coders-Central.github.io#28]
you are using Http. you need to use Https with an ssl certificate. but other then that is a good site. keep up the good work.
![image](https://user-images.githubusercontent.com/36646784/41943448-6008bcf4-799b-11e8-8452-40ef9cee2302.png)

see the securty risk and fix it.

**Comment by NE1W01F** [comment]
sorry it print screen printed both my screens lol

**Comment by ABaker86** [comment]
This is a very old site that I started working on with a group some years ago. As you can see it did not go very far.
