### ISSUE TITLE
Website Idea

### ISSUE THREAD

**Issue by SindhujaD** [Coders-Central/Coders-Central.github.io#7]
Do you guys think we could make our website like this, but functional? http://codepen.io/jlalovi/details/bIyAr We could use the code that is already there, and then make it work, so that when you click the "Messages" button, it works. We could make so that its like an email, news feed, E-Vite, twitter, facebook, and to keep up with new things combined. I also have saved a lot code from  CodePen that would be really useful for it, but there are still parts that we would need to add to make the website fully functional. Who knows..it could be the next big thing :) What do you think? Can we do it? We can always start with what we can do, then add on as we learn more...

**Comment by Solusin** [comment]
This a very good idea, but there are two issues I'm conflicting with. The first is the database. Unlike Facebook, Google, and Twitter, we have will have limitations of space allowed. The amount information being processed may cause trouble. Remember, We gotta have for every person signing up a page like this. Second. Just compare our page to that. Won't people spot a difference. I could code that page's CSS if I knew about the uses of webkits and so on, but its a good idea, if needed we can use this as inspiration.

**Comment by Solusin** [comment]
Oops.

**Comment by mektrode** [comment]
A good suggestion but c'mon guys i thought we were creating this website as a learning process and applying all that u have learned. I can easily manipulate the website to work with any cloud database but the key thing is an original idea we designed and developed.

**Comment by SindhujaD** [comment]
That's true...

**Comment by Solusin** [comment]
It is Sind, I commented out your search box, because of that factor.

**Comment by SindhujaD** [comment]
Okay, no problem.
