### ISSUE TITLE
Guys... Design Design Design

### ISSUE THREAD

**Issue by mektrode** [Coders-Central/Coders-Central.github.io#8]
Please Get hold of a Photoshop designer if any of you aren't in this project already. 

As soon as we decide on the type of content that's gonna be on the site we need a designer to create a lil something on Photoshop for us to code properly so we know where were going with this.

**Comment by ABaker86** [comment]
We don't actually need a Photoshop design. Web can simply use a responsive HTML and CSS theme. At the very least, we only need to know what the basic content of the site will be-including the number of pages(home, about, ect.). Give me a little time and I think that I can come up with something quite nice. However, I am wondering if the website's background image file is actually created by one of us or unlicensed, or does the image deserve accreditation?
