### ISSUE TITLE
CSS Link issue

### ISSUE THREAD

**Issue by Solusin** [Coders-Central/Coders-Central.github.io#9]
I can't figure it out, but the CSS isn't linking to the html, can anyone fix this?

**Comment by SindhujaD** [comment]
I don't know I've been having the same problem, I'll look it up.

**Comment by mektrode** [comment]
fixed.

**Comment by SindhujaD** [comment]
What was the problem? (So that we can avoid it next time)

**Comment by mektrode** [comment]
The link to the css sheet was wrong. it linked to "style.css" in the main
folder instead of "css/style.css" in the "css" sub folder. Check the commit
change
